FROM openjdk:21-jdk-slim

WORKDIR /app

COPY build/libs/dom-kotlin-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080 5005

ENTRYPOINT ["java", "-jar", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787", "app.jar"]
