version: "3.9"

services:
  dom-kotlin-service:
    image: dom-kotlin:1.0.0
    build:
      context: ../../
      dockerfile: Dockerfile-dom
    ports:
      - "8090:8080"
      - "8797:8787"
    environment:
      JVM_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: "512m"
          cpus: "0.5"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
