version: "3.9"

services:
  dom-kotlin-service:
    image: dom-kotlin:1.0.0
    build:
      context: ../../
      dockerfile: Dockerfile-dom
    ports:
      - "8090:8090"
      - "8797:8787"
    environment:
      JVM_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: "512m"
          cpus: "0.5"
